version: "3"

services:
  mc:
    image: itzg/minecraft-server:java8
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "CURSEFORGE"
      CF_SERVER_MOD: "/modpacks/ATM6-1.8.28-server.zip"
      FORGEVERSION: "36.2.29"
      VERSION: "1.16.5"
      MEMORY: "8G"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data
      - ./modpacks:/modpacks
